/** Popularne miasta PL — podpowiedzi do pola „Miasto” (alfabetycznie, pl). */
const POLISH_CITIES = [
  'Białystok',
  'Bielsko-Biała',
  'Bydgoszcz',
  'Chorzów',
  'Częstochowa',
  'Dąbrowa Górnicza',
  'Elbląg',
  'Gdańsk',
  'Gdynia',
  'Gliwice',
  'Gniezno',
  'Gorzów Wielkopolski',
  'Grudziądz',
  'Jastrzębie-Zdrój',
  'Jelenia Góra',
  'Kalisz',
  'Katowice',
  'Kielce',
  'Konin',
  'Koszalin',
  'Kraków',
  'Legnica',
  'Lublin',
  'Łódź',
  'Lubin',
  'Mysłowice',
  'Nowy Sącz',
  'Olsztyn',
  'Opole',
  'Ostrów Wielkopolski',
  'Ostrowiec Świętokrzyski',
  'Pabianice',
  'Piła',
  'Piotrków Trybunalski',
  'Płock',
  'Poznań',
  'Radom',
  'Ruda Śląska',
  'Rybnik',
  'Rzeszów',
  'Siemianowice Śląskie',
  'Sosnowiec',
  'Stargard',
  'Szczecin',
  'Tarnów',
  'Toruń',
  'Tychy',
  'Wałbrzych',
  'Warszawa',
  'Włocławek',
  'Wrocław',
  'Zabrze',
  'Zielona Góra',
  'Żory',
];

export function getPolishCityOptions() {
  return [...POLISH_CITIES].sort((a, b) => a.localeCompare(b, 'pl'));
}
