export const EVENT_CATEGORIES = [
  'Bieganie',
  'Joga',
  'CrossFit',
  'Pilates',
  'Stretching',
  'Kolarstwo',
  'Outdoor',
  'Kondycja',
  'Pływanie',
  'Kickboxing',
  'Taniec',
  'Trening funkcjonalny',
  'Fitness',
  'Siłownia',
  'Trening obwodowy',
  'Mobilność',
  'Kalistenika',
  'Sztuki walki',
  'Turystyka',
  'Tenis',
  'Piłka nożna',
  'Koszykówka',
  'Siatkówka',
  'Badminton',
  'Rolki',
  'Skakanka',
  'Boks',
  'Wspinaczka',
  'Nordic walking',
  'Inne',
];

/** Szybkie filtry na liście wydarzeń (bez „Inne”). */
export const POPULAR_CATEGORY_CHIPS = EVENT_CATEGORIES.filter((c) => c && c !== 'Inne').slice(0, 6);

